// Contact Properties in emailinformation.
import * as pulumi from "@pulumi/pulumi";
import { ContactProperty } from "../../../provider/contact_properties";

export const contactProperties = () => {
    const properties: any = {};

    properties["hs_email_quarantined"] = new ContactProperty("hs_email_quarantined", {
        // This field is used to indentify that this property was generated during importing existing properties.
        // Autogenerated fields are not editable. So if you try and change a value in this object you will fail.
        // If you want to edit this field, remove this field. Do so at your own peril.
        autoGeneratedViaImport: true,
        label: "Email Address Quarantined",
        description: "Indicates that the current email address has been quarantined for anti-abuse reasons and any marketing email sends to it will be blocked. This is automatically set by HubSpot.",
        groupName: "emailinformation",
        type: "bool",
        fieldType: "booleancheckbox",
        hidden: false,
        options: [{"doubleData":null,"label":"True","description":null,"hidden":false,"displayOrder":0,"readOnly":null,"value":"true"},{"doubleData":null,"label":"False","description":null,"hidden":false,"displayOrder":1,"readOnly":null,"value":"false"}],
        formField: false,
        displayOrder: -1,
        readOnlyDefinition: true,
        mutableDefinitionNotDeletable: false,
        calculated: false,
    });

    properties["hs_email_quarantined_reason"] = new ContactProperty("hs_email_quarantined_reason", {
        // This field is used to indentify that this property was generated during importing existing properties.
        // Autogenerated fields are not editable. So if you try and change a value in this object you will fail.
        // If you want to edit this field, remove this field. Do so at your own peril.
        autoGeneratedViaImport: true,
        label: "Email Address Quarantined Reason",
        description: "The reason why the email address has been quarantined. This is automatically set by HubSpot.",
        groupName: "emailinformation",
        type: "enumeration",
        fieldType: "checkbox",
        hidden: false,
        options: [{"doubleData":null,"label":"Other","description":null,"hidden":false,"displayOrder":-1,"readOnly":true,"value":"OTHER"},{"doubleData":null,"label":"Suspicious Form Activity","description":null,"hidden":false,"displayOrder":-1,"readOnly":true,"value":"FORM_ABUSE"}],
        formField: false,
        displayOrder: -1,
        readOnlyDefinition: true,
        mutableDefinitionNotDeletable: false,
        calculated: false,
    });

    properties["hs_email_sends_since_last_engagement"] = new ContactProperty("hs_email_sends_since_last_engagement", {
        // This field is used to indentify that this property was generated during importing existing properties.
        // Autogenerated fields are not editable. So if you try and change a value in this object you will fail.
        // If you want to edit this field, remove this field. Do so at your own peril.
        autoGeneratedViaImport: true,
        label: "Sends Since Last Engagement",
        description: "The number of marketing emails that have been sent to the current email address since the last engagement (open or link click). This is automatically set by HubSpot.",
        groupName: "emailinformation",
        type: "number",
        fieldType: "number",
        hidden: false,
        options: [],
        formField: false,
        displayOrder: -1,
        readOnlyDefinition: true,
        mutableDefinitionNotDeletable: false,
        calculated: false,
    });

    properties["hs_emailconfirmationstatus"] = new ContactProperty("hs_emailconfirmationstatus", {
        // This field is used to indentify that this property was generated during importing existing properties.
        // Autogenerated fields are not editable. So if you try and change a value in this object you will fail.
        // If you want to edit this field, remove this field. Do so at your own peril.
        autoGeneratedViaImport: true,
        label: "Marketing email confirmation status",
        description: "The status of a contact's eligibility to receive marketing email. This is automatically set by HubSpot.",
        groupName: "emailinformation",
        type: "enumeration",
        fieldType: "select",
        hidden: false,
        options: [{"doubleData":null,"label":"","description":null,"hidden":false,"displayOrder":1,"readOnly":null,"value":""},{"doubleData":null,"label":"Confirmed","description":null,"hidden":false,"displayOrder":2,"readOnly":null,"value":"Confirmed"},{"doubleData":null,"label":"Confirmation Pending","description":null,"hidden":false,"displayOrder":3,"readOnly":null,"value":"Confirmation Pending"},{"doubleData":null,"label":"Confirmation Email Sent","description":null,"hidden":false,"displayOrder":4,"readOnly":null,"value":"Confirmation Email Sent"},{"doubleData":null,"label":"User clicked confirmation","description":null,"hidden":false,"displayOrder":6,"readOnly":null,"value":"User clicked confirmation"},{"doubleData":null,"label":"HubSpot Rep. marked confirmed","description":null,"hidden":false,"displayOrder":7,"readOnly":null,"value":"HubSpot Rep. marked confirmed"},{"doubleData":null,"label":"Customer marked confirmed","description":null,"hidden":false,"displayOrder":8,"readOnly":null,"value":"Customer marked confirmed"},{"doubleData":null,"label":"Confirmed from previous behavior","description":null,"hidden":false,"displayOrder":9,"readOnly":null,"value":"Confirmed from previous behavior"},{"doubleData":null,"label":"Confirmed due to form","description":null,"hidden":false,"displayOrder":11,"readOnly":null,"value":"Confirmed due to form"}],
        formField: false,
        displayOrder: -1,
        readOnlyDefinition: true,
        mutableDefinitionNotDeletable: false,
        calculated: false,
    });

    properties["hs_email_delivered"] = new ContactProperty("hs_email_delivered", {
        // This field is used to indentify that this property was generated during importing existing properties.
        // Autogenerated fields are not editable. So if you try and change a value in this object you will fail.
        // If you want to edit this field, remove this field. Do so at your own peril.
        autoGeneratedViaImport: true,
        label: "Marketing emails delivered",
        description: "The number of marketing emails delivered for the current email address. This is automatically set by HubSpot.",
        groupName: "emailinformation",
        type: "number",
        fieldType: "number",
        hidden: false,
        options: [],
        formField: false,
        displayOrder: 0,
        readOnlyDefinition: true,
        mutableDefinitionNotDeletable: false,
        calculated: false,
    });

    properties["hs_email_optout_7610754"] = new ContactProperty("hs_email_optout_7610754", {
        // This field is used to indentify that this property was generated during importing existing properties.
        // Autogenerated fields are not editable. So if you try and change a value in this object you will fail.
        // If you want to edit this field, remove this field. Do so at your own peril.
        autoGeneratedViaImport: true,
        label: "Opted out of email: Marketing Information",
        description: "Indicates that the current email address has opted out of this email type.",
        groupName: "emailinformation",
        type: "enumeration",
        fieldType: "booleancheckbox",
        hidden: false,
        options: [{"doubleData":null,"label":"No","description":null,"hidden":false,"displayOrder":-1,"readOnly":null,"value":"false"},{"doubleData":null,"label":"Yes","description":null,"hidden":false,"displayOrder":-1,"readOnly":null,"value":"true"}],
        formField: false,
        displayOrder: 0,
        readOnlyDefinition: true,
        mutableDefinitionNotDeletable: false,
        calculated: false,
    });

    properties["hs_email_open"] = new ContactProperty("hs_email_open", {
        // This field is used to indentify that this property was generated during importing existing properties.
        // Autogenerated fields are not editable. So if you try and change a value in this object you will fail.
        // If you want to edit this field, remove this field. Do so at your own peril.
        autoGeneratedViaImport: true,
        label: "Marketing emails opened",
        description: "The number of marketing emails opened for the current email address. This is automatically set by HubSpot.",
        groupName: "emailinformation",
        type: "number",
        fieldType: "number",
        hidden: false,
        options: [],
        formField: false,
        displayOrder: 1,
        readOnlyDefinition: true,
        mutableDefinitionNotDeletable: false,
        calculated: false,
    });

    properties["hs_email_click"] = new ContactProperty("hs_email_click", {
        // This field is used to indentify that this property was generated during importing existing properties.
        // Autogenerated fields are not editable. So if you try and change a value in this object you will fail.
        // If you want to edit this field, remove this field. Do so at your own peril.
        autoGeneratedViaImport: true,
        label: "Marketing emails clicked",
        description: "The number of marketing emails which have had link clicks for the current email address. This is automatically set by HubSpot.",
        groupName: "emailinformation",
        type: "number",
        fieldType: "number",
        hidden: false,
        options: [],
        formField: false,
        displayOrder: 2,
        readOnlyDefinition: true,
        mutableDefinitionNotDeletable: false,
        calculated: false,
    });

    properties["hs_email_bounce"] = new ContactProperty("hs_email_bounce", {
        // This field is used to indentify that this property was generated during importing existing properties.
        // Autogenerated fields are not editable. So if you try and change a value in this object you will fail.
        // If you want to edit this field, remove this field. Do so at your own peril.
        autoGeneratedViaImport: true,
        label: "Marketing emails bounced",
        description: "The number of marketing emails that bounced for the current email address. This is automatically set by HubSpot.",
        groupName: "emailinformation",
        type: "number",
        fieldType: "number",
        hidden: false,
        options: [],
        formField: false,
        displayOrder: 3,
        readOnlyDefinition: true,
        mutableDefinitionNotDeletable: false,
        calculated: false,
    });

    properties["hs_email_optout"] = new ContactProperty("hs_email_optout", {
        // This field is used to indentify that this property was generated during importing existing properties.
        // Autogenerated fields are not editable. So if you try and change a value in this object you will fail.
        // If you want to edit this field, remove this field. Do so at your own peril.
        autoGeneratedViaImport: true,
        label: "Unsubscribed from all email",
        description: "Indicates that the current email address has opted out of all email.",
        groupName: "emailinformation",
        type: "bool",
        fieldType: "booleancheckbox",
        hidden: false,
        options: [{"doubleData":null,"label":"True","description":null,"hidden":false,"displayOrder":0,"readOnly":null,"value":"true"},{"doubleData":null,"label":"False","description":null,"hidden":false,"displayOrder":1,"readOnly":null,"value":"false"}],
        formField: false,
        displayOrder: 4,
        readOnlyDefinition: true,
        mutableDefinitionNotDeletable: false,
        calculated: false,
    });

    properties["hs_email_last_email_name"] = new ContactProperty("hs_email_last_email_name", {
        // This field is used to indentify that this property was generated during importing existing properties.
        // Autogenerated fields are not editable. So if you try and change a value in this object you will fail.
        // If you want to edit this field, remove this field. Do so at your own peril.
        autoGeneratedViaImport: true,
        label: "Last marketing email name",
        description: "The name of the last marketing email sent to the current email address. This is automatically set by HubSpot.",
        groupName: "emailinformation",
        type: "string",
        fieldType: "text",
        hidden: false,
        options: [],
        formField: false,
        displayOrder: 5,
        readOnlyDefinition: true,
        mutableDefinitionNotDeletable: false,
        calculated: false,
    });

    properties["hs_email_last_send_date"] = new ContactProperty("hs_email_last_send_date", {
        // This field is used to indentify that this property was generated during importing existing properties.
        // Autogenerated fields are not editable. So if you try and change a value in this object you will fail.
        // If you want to edit this field, remove this field. Do so at your own peril.
        autoGeneratedViaImport: true,
        label: "Last marketing email send date",
        description: "The date of the most recent delivery for any marketing email to the current email address. This is automatically set by HubSpot.",
        groupName: "emailinformation",
        type: "datetime",
        fieldType: "date",
        hidden: false,
        options: [],
        formField: false,
        displayOrder: 5,
        readOnlyDefinition: true,
        mutableDefinitionNotDeletable: false,
        calculated: false,
    });

    properties["hs_email_last_open_date"] = new ContactProperty("hs_email_last_open_date", {
        // This field is used to indentify that this property was generated during importing existing properties.
        // Autogenerated fields are not editable. So if you try and change a value in this object you will fail.
        // If you want to edit this field, remove this field. Do so at your own peril.
        autoGeneratedViaImport: true,
        label: "Last marketing email open date",
        description: "The date of the most recent open for any marketing email to the current email address. This is automatically set by HubSpot.",
        groupName: "emailinformation",
        type: "datetime",
        fieldType: "date",
        hidden: false,
        options: [],
        formField: false,
        displayOrder: 6,
        readOnlyDefinition: true,
        mutableDefinitionNotDeletable: false,
        calculated: false,
    });

    properties["hs_email_last_click_date"] = new ContactProperty("hs_email_last_click_date", {
        // This field is used to indentify that this property was generated during importing existing properties.
        // Autogenerated fields are not editable. So if you try and change a value in this object you will fail.
        // If you want to edit this field, remove this field. Do so at your own peril.
        autoGeneratedViaImport: true,
        label: "Last marketing email click date",
        description: "The date of the most recent link click for any marketing email to the current email address. This is automatically set by HubSpot.",
        groupName: "emailinformation",
        type: "datetime",
        fieldType: "date",
        hidden: false,
        options: [],
        formField: false,
        displayOrder: 7,
        readOnlyDefinition: true,
        mutableDefinitionNotDeletable: false,
        calculated: false,
    });

    properties["hs_email_first_send_date"] = new ContactProperty("hs_email_first_send_date", {
        // This field is used to indentify that this property was generated during importing existing properties.
        // Autogenerated fields are not editable. So if you try and change a value in this object you will fail.
        // If you want to edit this field, remove this field. Do so at your own peril.
        autoGeneratedViaImport: true,
        label: "First marketing email send date",
        description: "The date of the earliest delivery for any marketing email to the current email address. This is automatically set by HubSpot.",
        groupName: "emailinformation",
        type: "datetime",
        fieldType: "date",
        hidden: false,
        options: [],
        formField: false,
        displayOrder: 8,
        readOnlyDefinition: true,
        mutableDefinitionNotDeletable: false,
        calculated: false,
    });

    properties["hs_email_first_open_date"] = new ContactProperty("hs_email_first_open_date", {
        // This field is used to indentify that this property was generated during importing existing properties.
        // Autogenerated fields are not editable. So if you try and change a value in this object you will fail.
        // If you want to edit this field, remove this field. Do so at your own peril.
        autoGeneratedViaImport: true,
        label: "First marketing email open date",
        description: "The date of the earliest open for any marketing email to the current email address. This is automatically set by HubSpot.",
        groupName: "emailinformation",
        type: "datetime",
        fieldType: "date",
        hidden: false,
        options: [],
        formField: false,
        displayOrder: 9,
        readOnlyDefinition: true,
        mutableDefinitionNotDeletable: false,
        calculated: false,
    });

    properties["hs_email_first_click_date"] = new ContactProperty("hs_email_first_click_date", {
        // This field is used to indentify that this property was generated during importing existing properties.
        // Autogenerated fields are not editable. So if you try and change a value in this object you will fail.
        // If you want to edit this field, remove this field. Do so at your own peril.
        autoGeneratedViaImport: true,
        label: "First marketing email click date",
        description: "The date of the earliest link click for any marketing email to the current email address. This is automatically set by HubSpot.",
        groupName: "emailinformation",
        type: "datetime",
        fieldType: "date",
        hidden: false,
        options: [],
        formField: false,
        displayOrder: 10,
        readOnlyDefinition: true,
        mutableDefinitionNotDeletable: false,
        calculated: false,
    });

    properties["hs_email_is_ineligible"] = new ContactProperty("hs_email_is_ineligible", {
        // This field is used to indentify that this property was generated during importing existing properties.
        // Autogenerated fields are not editable. So if you try and change a value in this object you will fail.
        // If you want to edit this field, remove this field. Do so at your own peril.
        autoGeneratedViaImport: true,
        label: "Is globally ineligible",
        description: "Indicates the contact is globally ineligible for email.",
        groupName: "emailinformation",
        type: "bool",
        fieldType: "booleancheckbox",
        hidden: true,
        options: [{"doubleData":null,"label":"True","description":null,"hidden":false,"displayOrder":0,"readOnly":null,"value":"true"},{"doubleData":null,"label":"False","description":null,"hidden":false,"displayOrder":1,"readOnly":null,"value":"false"}],
        formField: false,
        displayOrder: 11,
        readOnlyDefinition: true,
        mutableDefinitionNotDeletable: false,
        calculated: false,
    });

    return properties;
};
