import * as fs from "fs";
import { HubSpotClient } from "../provider/hubspot_client";
import { ContactPropertyProps } from "../../types/ContactProperty";

export async function getCurrentContactProperties(): Promise<any[]> {
    const hsClient = new HubSpotClient();
    const [ err, contactProperties ] = await hsClient.get("/properties/v1/contacts/properties");
    if (err) {
        throw new Error("Error fetching current contact properties: " + err?.response?.data?.message);
    }

    return contactProperties as any[];
}

function buildArgs(props: any, keys: string[]): string {
    let result = "";
    const propsKeys = Object.keys(props);

    for (let i = 0; i < propsKeys.length; i++) {
        const propKey = propsKeys[i];
        if (keys.indexOf(propKey) > -1) {
            const value = JSON.stringify(props[propKey])
            result += `        ${propKey}: ${value},\n`;
        }
    }

    return result;
}

function generateContactPropertyFunction(prop: any) {
    const buildArgsKeys = [
        "name", "label", "groupName", "type", "fieldType", "description", "formField", "displayOrder",
        "mutableDefinitionNotDeletable", "readOnly", "readOnlyDefinition", "hidden", "options", "calculated"
    ];
    return "\n" +
           `    properties["${prop.name}"] = new ContactProperty("${prop.name}", {\n` +
           `        // This field is used to indentify that this property was generated during importing existing properties.\n` +
           `        // Autogenerated fields are not editable. So if you try and change a value in this object you will fail.\n` +
           `        // If you want to edit this field, remove this field. Do so at your own peril.\n` +
           `        autoGeneratedViaImport: true,\n` +
           buildArgs(prop, buildArgsKeys) +
           `    });\n`;
}

export function generateContactPropertyTS(props: any[]) {
    console.log(Object.keys(props));
    let file = "// Contact Properties.\n" +
               "import * as pulumi from \"@pulumi/pulumi\";\n" +
               "import { ContactProperty } from \"../provider/contact_properties\";\n\n" +
               "const contactProperties = () => {\n" +
               "    const properties: any = {};\n";

    for (let i = 0; i < props.length; i++) {
        file += generateContactPropertyFunction(props[i]);
    }

    file += "\n" +
            "    return properties;\n" +
            "};\n\n" +
            "export { contactProperties };\n";

    fs.writeFileSync("./src/hubspot/hs_contact_properties.ts", file);
}
