// Contact Properties in analyticsinformation.
import * as pulumi from "@pulumi/pulumi";
import { ContactProperty } from "../../../provider/contact_properties";

export const contactProperties = () => {
    const properties: any = {};

    properties["hs_analytics_first_touch_converting_campaign"] = new ContactProperty("hs_analytics_first_touch_converting_campaign", {
        // This field is used to indentify that this property was generated during importing existing properties.
        // Autogenerated fields are not editable. So if you try and change a value in this object you will fail.
        // If you want to edit this field, remove this field. Do so at your own peril.
        autoGeneratedViaImport: true,
        label: "First Touch Converting Campaign",
        description: "The campaign responsible for the first touch creation of this contact",
        groupName: "analyticsinformation",
        type: "string",
        fieldType: "text",
        hidden: false,
        options: [],
        formField: false,
        displayOrder: -1,
        readOnlyDefinition: true,
        mutableDefinitionNotDeletable: false,
        calculated: false,
    });

    properties["hs_analytics_last_touch_converting_campaign"] = new ContactProperty("hs_analytics_last_touch_converting_campaign", {
        // This field is used to indentify that this property was generated during importing existing properties.
        // Autogenerated fields are not editable. So if you try and change a value in this object you will fail.
        // If you want to edit this field, remove this field. Do so at your own peril.
        autoGeneratedViaImport: true,
        label: "Last Touch Converting Campaign",
        description: "The campaign responsible for the last touch creation of this contact",
        groupName: "analyticsinformation",
        type: "string",
        fieldType: "text",
        hidden: false,
        options: [],
        formField: false,
        displayOrder: -1,
        readOnlyDefinition: true,
        mutableDefinitionNotDeletable: false,
        calculated: false,
    });

    properties["last_utm_campaign"] = new ContactProperty("last_utm_campaign", {
        // This field is used to indentify that this property was generated during importing existing properties.
        // Autogenerated fields are not editable. So if you try and change a value in this object you will fail.
        // If you want to edit this field, remove this field. Do so at your own peril.
        autoGeneratedViaImport: true,
        label: "Last UTM Campaign",
        description: "Currently only tracked for app registrations.",
        groupName: "analyticsinformation",
        type: "string",
        fieldType: "text",
        hidden: false,
        options: [],
        formField: false,
        displayOrder: -1,
        readOnlyDefinition: false,
        mutableDefinitionNotDeletable: false,
        calculated: false,
    });

    properties["last_utm_medium"] = new ContactProperty("last_utm_medium", {
        // This field is used to indentify that this property was generated during importing existing properties.
        // Autogenerated fields are not editable. So if you try and change a value in this object you will fail.
        // If you want to edit this field, remove this field. Do so at your own peril.
        autoGeneratedViaImport: true,
        label: "Last UTM Medium",
        description: "Currently only tracked for app registrations.",
        groupName: "analyticsinformation",
        type: "string",
        fieldType: "text",
        hidden: false,
        options: [],
        formField: true,
        displayOrder: -1,
        readOnlyDefinition: false,
        mutableDefinitionNotDeletable: false,
        calculated: false,
    });

    properties["last_utm_source"] = new ContactProperty("last_utm_source", {
        // This field is used to indentify that this property was generated during importing existing properties.
        // Autogenerated fields are not editable. So if you try and change a value in this object you will fail.
        // If you want to edit this field, remove this field. Do so at your own peril.
        autoGeneratedViaImport: true,
        label: "Last UTM Source",
        description: "Currently only tracked for app registrations.",
        groupName: "analyticsinformation",
        type: "string",
        fieldType: "text",
        hidden: false,
        options: [],
        formField: true,
        displayOrder: -1,
        readOnlyDefinition: false,
        mutableDefinitionNotDeletable: false,
        calculated: false,
    });

    properties["hs_analytics_first_url"] = new ContactProperty("hs_analytics_first_url", {
        // This field is used to indentify that this property was generated during importing existing properties.
        // Autogenerated fields are not editable. So if you try and change a value in this object you will fail.
        // If you want to edit this field, remove this field. Do so at your own peril.
        autoGeneratedViaImport: true,
        label: "First Page Seen",
        description: "The first page a contact saw on your website. This is automatically set by HubSpot for each contact.",
        groupName: "analyticsinformation",
        type: "string",
        fieldType: "text",
        hidden: false,
        options: [],
        formField: false,
        displayOrder: 0,
        readOnlyDefinition: true,
        mutableDefinitionNotDeletable: false,
        calculated: false,
    });

    properties["hs_analytics_last_url"] = new ContactProperty("hs_analytics_last_url", {
        // This field is used to indentify that this property was generated during importing existing properties.
        // Autogenerated fields are not editable. So if you try and change a value in this object you will fail.
        // If you want to edit this field, remove this field. Do so at your own peril.
        autoGeneratedViaImport: true,
        label: "Last Page Seen",
        description: "The last page a contact saw on your website. This is automatically set by HubSpot for each contact.",
        groupName: "analyticsinformation",
        type: "string",
        fieldType: "text",
        hidden: false,
        options: [],
        formField: false,
        displayOrder: 1,
        readOnlyDefinition: true,
        mutableDefinitionNotDeletable: false,
        calculated: false,
    });

    properties["hs_analytics_num_page_views"] = new ContactProperty("hs_analytics_num_page_views", {
        // This field is used to indentify that this property was generated during importing existing properties.
        // Autogenerated fields are not editable. So if you try and change a value in this object you will fail.
        // If you want to edit this field, remove this field. Do so at your own peril.
        autoGeneratedViaImport: true,
        label: "Number of Pageviews",
        description: "The sum of all pages a contact has seen on your website. This is automatically set by HubSpot for each contact.",
        groupName: "analyticsinformation",
        type: "number",
        fieldType: "number",
        hidden: false,
        options: [],
        formField: false,
        displayOrder: 2,
        readOnlyDefinition: true,
        mutableDefinitionNotDeletable: false,
        calculated: false,
    });

    properties["hs_analytics_num_visits"] = new ContactProperty("hs_analytics_num_visits", {
        // This field is used to indentify that this property was generated during importing existing properties.
        // Autogenerated fields are not editable. So if you try and change a value in this object you will fail.
        // If you want to edit this field, remove this field. Do so at your own peril.
        autoGeneratedViaImport: true,
        label: "Number of Sessions",
        description: "The sum of all sessions a contact has made to your website. This is automatically set by HubSpot for each contact.",
        groupName: "analyticsinformation",
        type: "number",
        fieldType: "number",
        hidden: false,
        options: [],
        formField: false,
        displayOrder: 3,
        readOnlyDefinition: true,
        mutableDefinitionNotDeletable: false,
        calculated: false,
    });

    properties["hs_analytics_num_event_completions"] = new ContactProperty("hs_analytics_num_event_completions", {
        // This field is used to indentify that this property was generated during importing existing properties.
        // Autogenerated fields are not editable. So if you try and change a value in this object you will fail.
        // If you want to edit this field, remove this field. Do so at your own peril.
        autoGeneratedViaImport: true,
        label: "Number of event completions",
        description: "The sum of all events a contact has experienced. This is automatically set by HubSpot for each contact.",
        groupName: "analyticsinformation",
        type: "number",
        fieldType: "number",
        hidden: false,
        options: [],
        formField: false,
        displayOrder: 4,
        readOnlyDefinition: true,
        mutableDefinitionNotDeletable: false,
        calculated: false,
    });

    properties["hs_analytics_first_timestamp"] = new ContactProperty("hs_analytics_first_timestamp", {
        // This field is used to indentify that this property was generated during importing existing properties.
        // Autogenerated fields are not editable. So if you try and change a value in this object you will fail.
        // If you want to edit this field, remove this field. Do so at your own peril.
        autoGeneratedViaImport: true,
        label: "Time First Seen",
        description: "The first time a contact has been seen. This is automatically set by HubSpot for each contact.",
        groupName: "analyticsinformation",
        type: "datetime",
        fieldType: "date",
        hidden: false,
        options: [],
        formField: false,
        displayOrder: 5,
        readOnlyDefinition: true,
        mutableDefinitionNotDeletable: false,
        calculated: false,
    });

    properties["hs_analytics_first_visit_timestamp"] = new ContactProperty("hs_analytics_first_visit_timestamp", {
        // This field is used to indentify that this property was generated during importing existing properties.
        // Autogenerated fields are not editable. So if you try and change a value in this object you will fail.
        // If you want to edit this field, remove this field. Do so at your own peril.
        autoGeneratedViaImport: true,
        label: "Time of First Session",
        description: "The first time a contact visited your website. This is automatically set by HubSpot for each contact.",
        groupName: "analyticsinformation",
        type: "datetime",
        fieldType: "date",
        hidden: false,
        options: [],
        formField: false,
        displayOrder: 6,
        readOnlyDefinition: true,
        mutableDefinitionNotDeletable: false,
        calculated: false,
    });

    properties["hs_analytics_last_timestamp"] = new ContactProperty("hs_analytics_last_timestamp", {
        // This field is used to indentify that this property was generated during importing existing properties.
        // Autogenerated fields are not editable. So if you try and change a value in this object you will fail.
        // If you want to edit this field, remove this field. Do so at your own peril.
        autoGeneratedViaImport: true,
        label: "Time Last Seen",
        description: "The last time and date a contact has viewed a page on your website.",
        groupName: "analyticsinformation",
        type: "datetime",
        fieldType: "date",
        hidden: false,
        options: [],
        formField: false,
        displayOrder: 7,
        readOnlyDefinition: true,
        mutableDefinitionNotDeletable: false,
        calculated: false,
    });

    properties["hs_analytics_last_visit_timestamp"] = new ContactProperty("hs_analytics_last_visit_timestamp", {
        // This field is used to indentify that this property was generated during importing existing properties.
        // Autogenerated fields are not editable. So if you try and change a value in this object you will fail.
        // If you want to edit this field, remove this field. Do so at your own peril.
        autoGeneratedViaImport: true,
        label: "Time of Last Session",
        description: "The last time and date a contact visited your website.",
        groupName: "analyticsinformation",
        type: "datetime",
        fieldType: "date",
        hidden: false,
        options: [],
        formField: false,
        displayOrder: 8,
        readOnlyDefinition: true,
        mutableDefinitionNotDeletable: false,
        calculated: false,
    });

    properties["hs_analytics_source"] = new ContactProperty("hs_analytics_source", {
        // This field is used to indentify that this property was generated during importing existing properties.
        // Autogenerated fields are not editable. So if you try and change a value in this object you will fail.
        // If you want to edit this field, remove this field. Do so at your own peril.
        autoGeneratedViaImport: true,
        label: "Original Source",
        description: "The first known source through which a contact found your website. Source is automatically set by HubSpot, but may be updated manually.",
        groupName: "analyticsinformation",
        type: "enumeration",
        fieldType: "select",
        hidden: false,
        options: [{"doubleData":null,"label":"Organic Search","description":null,"hidden":false,"displayOrder":0,"readOnly":null,"value":"ORGANIC_SEARCH"},{"doubleData":null,"label":"Paid Search","description":null,"hidden":false,"displayOrder":1,"readOnly":null,"value":"PAID_SEARCH"},{"doubleData":null,"label":"Email Marketing","description":null,"hidden":false,"displayOrder":2,"readOnly":null,"value":"EMAIL_MARKETING"},{"doubleData":null,"label":"Social Media","description":null,"hidden":false,"displayOrder":3,"readOnly":null,"value":"SOCIAL_MEDIA"},{"doubleData":null,"label":"Referrals","description":null,"hidden":false,"displayOrder":4,"readOnly":null,"value":"REFERRALS"},{"doubleData":null,"label":"Other Campaigns","description":null,"hidden":false,"displayOrder":5,"readOnly":null,"value":"OTHER_CAMPAIGNS"},{"doubleData":null,"label":"Direct Traffic","description":null,"hidden":false,"displayOrder":6,"readOnly":null,"value":"DIRECT_TRAFFIC"},{"doubleData":null,"label":"Offline Sources","description":null,"hidden":false,"displayOrder":7,"readOnly":null,"value":"OFFLINE"},{"doubleData":null,"label":"Paid Social","description":null,"hidden":false,"displayOrder":8,"readOnly":null,"value":"PAID_SOCIAL"}],
        formField: false,
        displayOrder: 9,
        readOnlyDefinition: true,
        mutableDefinitionNotDeletable: false,
        calculated: false,
    });

    properties["hs_analytics_source_data_1"] = new ContactProperty("hs_analytics_source_data_1", {
        // This field is used to indentify that this property was generated during importing existing properties.
        // Autogenerated fields are not editable. So if you try and change a value in this object you will fail.
        // If you want to edit this field, remove this field. Do so at your own peril.
        autoGeneratedViaImport: true,
        label: "Original Source Drill-Down 1",
        description: "Additional information about the source through which a contact first found your website. This property is automatically set by HubSpot.",
        groupName: "analyticsinformation",
        type: "string",
        fieldType: "text",
        hidden: false,
        options: [],
        formField: false,
        displayOrder: 10,
        readOnlyDefinition: true,
        mutableDefinitionNotDeletable: false,
        calculated: false,
    });

    properties["hs_analytics_source_data_2"] = new ContactProperty("hs_analytics_source_data_2", {
        // This field is used to indentify that this property was generated during importing existing properties.
        // Autogenerated fields are not editable. So if you try and change a value in this object you will fail.
        // If you want to edit this field, remove this field. Do so at your own peril.
        autoGeneratedViaImport: true,
        label: "Original Source Drill-Down 2",
        description: "Additional information about the source through which a contact first found your website. This property is automatically set by HubSpot.",
        groupName: "analyticsinformation",
        type: "string",
        fieldType: "text",
        hidden: false,
        options: [],
        formField: false,
        displayOrder: 11,
        readOnlyDefinition: true,
        mutableDefinitionNotDeletable: false,
        calculated: false,
    });

    properties["hs_analytics_first_referrer"] = new ContactProperty("hs_analytics_first_referrer", {
        // This field is used to indentify that this property was generated during importing existing properties.
        // Autogenerated fields are not editable. So if you try and change a value in this object you will fail.
        // If you want to edit this field, remove this field. Do so at your own peril.
        autoGeneratedViaImport: true,
        label: "First Referring Site",
        description: "The first website that referred a contact to your website. This is automatically set by HubSpot for each contact.",
        groupName: "analyticsinformation",
        type: "string",
        fieldType: "text",
        hidden: false,
        options: [],
        formField: false,
        displayOrder: 12,
        readOnlyDefinition: true,
        mutableDefinitionNotDeletable: false,
        calculated: false,
    });

    properties["hs_analytics_last_referrer"] = new ContactProperty("hs_analytics_last_referrer", {
        // This field is used to indentify that this property was generated during importing existing properties.
        // Autogenerated fields are not editable. So if you try and change a value in this object you will fail.
        // If you want to edit this field, remove this field. Do so at your own peril.
        autoGeneratedViaImport: true,
        label: "Last Referring Site",
        description: "The last website that referred a contact to your website. This is automatically set by HubSpot for each contact.",
        groupName: "analyticsinformation",
        type: "string",
        fieldType: "text",
        hidden: false,
        options: [],
        formField: false,
        displayOrder: 13,
        readOnlyDefinition: true,
        mutableDefinitionNotDeletable: false,
        calculated: false,
    });

    properties["hs_analytics_average_page_views"] = new ContactProperty("hs_analytics_average_page_views", {
        // This field is used to indentify that this property was generated during importing existing properties.
        // Autogenerated fields are not editable. So if you try and change a value in this object you will fail.
        // If you want to edit this field, remove this field. Do so at your own peril.
        autoGeneratedViaImport: true,
        label: "Average Pageviews",
        description: "The average number of pages a contact sees. This is automatically set by HubSpot for each contact.",
        groupName: "analyticsinformation",
        type: "number",
        fieldType: "number",
        hidden: false,
        options: [],
        formField: false,
        displayOrder: 14,
        readOnlyDefinition: true,
        mutableDefinitionNotDeletable: false,
        calculated: false,
    });

    properties["hs_analytics_revenue"] = new ContactProperty("hs_analytics_revenue", {
        // This field is used to indentify that this property was generated during importing existing properties.
        // Autogenerated fields are not editable. So if you try and change a value in this object you will fail.
        // If you want to edit this field, remove this field. Do so at your own peril.
        autoGeneratedViaImport: true,
        label: "Event Revenue",
        description: "Event revenue can be set on a contact though HubSpot's enterprise Events. http://help.hubspot.com/articles/KCS_Article/Reports/How-do-I-create-Events-in-HubSpot",
        groupName: "analyticsinformation",
        type: "number",
        fieldType: "number",
        hidden: false,
        options: [],
        formField: false,
        displayOrder: 15,
        readOnlyDefinition: true,
        mutableDefinitionNotDeletable: false,
        calculated: false,
    });

    return properties;
};
