// Contact Properties in conversioninformation.
import * as pulumi from "@pulumi/pulumi";
import { ContactProperty } from "../../../provider/contact_properties";

export const contactProperties = () => {
    const properties: any = {};

    properties["first_conversion_date"] = new ContactProperty("first_conversion_date", {
        // This field is used to indentify that this property was generated during importing existing properties.
        // Autogenerated fields are not editable. So if you try and change a value in this object you will fail.
        // If you want to edit this field, remove this field. Do so at your own peril.
        autoGeneratedViaImport: true,
        label: "First Conversion Date",
        description: "The date this contact first submitted a form",
        groupName: "conversioninformation",
        type: "datetime",
        fieldType: "date",
        hidden: false,
        options: [],
        formField: false,
        displayOrder: -1,
        readOnlyDefinition: true,
        mutableDefinitionNotDeletable: false,
        calculated: true,
    });

    properties["first_conversion_event_name"] = new ContactProperty("first_conversion_event_name", {
        // This field is used to indentify that this property was generated during importing existing properties.
        // Autogenerated fields are not editable. So if you try and change a value in this object you will fail.
        // If you want to edit this field, remove this field. Do so at your own peril.
        autoGeneratedViaImport: true,
        label: "First Conversion",
        description: "The first form this contact submitted",
        groupName: "conversioninformation",
        type: "string",
        fieldType: "text",
        hidden: false,
        options: [],
        formField: false,
        displayOrder: -1,
        readOnlyDefinition: true,
        mutableDefinitionNotDeletable: false,
        calculated: true,
    });

    properties["hs_facebook_ad_clicked"] = new ContactProperty("hs_facebook_ad_clicked", {
        // This field is used to indentify that this property was generated during importing existing properties.
        // Autogenerated fields are not editable. So if you try and change a value in this object you will fail.
        // If you want to edit this field, remove this field. Do so at your own peril.
        autoGeneratedViaImport: true,
        label: "Clicked Facebook ad",
        description: "Whether contact has clicked a Facebook ad",
        groupName: "conversioninformation",
        type: "bool",
        fieldType: "booleancheckbox",
        hidden: true,
        options: [{"doubleData":null,"label":"True","description":null,"hidden":false,"displayOrder":0,"readOnly":null,"value":"true"},{"doubleData":null,"label":"False","description":null,"hidden":false,"displayOrder":1,"readOnly":null,"value":"false"}],
        formField: false,
        displayOrder: -1,
        readOnlyDefinition: false,
        mutableDefinitionNotDeletable: true,
        calculated: false,
    });

    properties["hs_google_click_id"] = new ContactProperty("hs_google_click_id", {
        // This field is used to indentify that this property was generated during importing existing properties.
        // Autogenerated fields are not editable. So if you try and change a value in this object you will fail.
        // If you want to edit this field, remove this field. Do so at your own peril.
        autoGeneratedViaImport: true,
        label: "Google ad click id",
        description: "",
        groupName: "conversioninformation",
        type: "string",
        fieldType: "text",
        hidden: true,
        options: [],
        formField: false,
        displayOrder: -1,
        readOnlyDefinition: false,
        mutableDefinitionNotDeletable: true,
        calculated: false,
    });

    properties["hs_ip_timezone"] = new ContactProperty("hs_ip_timezone", {
        // This field is used to indentify that this property was generated during importing existing properties.
        // Autogenerated fields are not editable. So if you try and change a value in this object you will fail.
        // If you want to edit this field, remove this field. Do so at your own peril.
        autoGeneratedViaImport: true,
        label: "IP Timezone",
        description: "The timezone reported by a contact's IP address. This is automatically set by HubSpot and can be used for segmentation and reporting.",
        groupName: "conversioninformation",
        type: "string",
        fieldType: "text",
        hidden: false,
        options: [],
        formField: false,
        displayOrder: -1,
        readOnlyDefinition: true,
        mutableDefinitionNotDeletable: false,
        calculated: false,
    });

    properties["ip_city"] = new ContactProperty("ip_city", {
        // This field is used to indentify that this property was generated during importing existing properties.
        // Autogenerated fields are not editable. So if you try and change a value in this object you will fail.
        // If you want to edit this field, remove this field. Do so at your own peril.
        autoGeneratedViaImport: true,
        label: "IP City",
        description: "The city reported by a contact's IP address. This is automatically set by HubSpot and can be used for segmentation and reporting.",
        groupName: "conversioninformation",
        type: "string",
        fieldType: "text",
        hidden: false,
        options: [],
        formField: false,
        displayOrder: -1,
        readOnlyDefinition: true,
        mutableDefinitionNotDeletable: false,
        calculated: false,
    });

    properties["ip_country"] = new ContactProperty("ip_country", {
        // This field is used to indentify that this property was generated during importing existing properties.
        // Autogenerated fields are not editable. So if you try and change a value in this object you will fail.
        // If you want to edit this field, remove this field. Do so at your own peril.
        autoGeneratedViaImport: true,
        label: "IP Country",
        description: "The country reported by a contact's IP address. This is automatically set by HubSpot and can be used for segmentation and reporting.",
        groupName: "conversioninformation",
        type: "string",
        fieldType: "text",
        hidden: false,
        options: [],
        formField: false,
        displayOrder: -1,
        readOnlyDefinition: true,
        mutableDefinitionNotDeletable: false,
        calculated: false,
    });

    properties["ip_country_code"] = new ContactProperty("ip_country_code", {
        // This field is used to indentify that this property was generated during importing existing properties.
        // Autogenerated fields are not editable. So if you try and change a value in this object you will fail.
        // If you want to edit this field, remove this field. Do so at your own peril.
        autoGeneratedViaImport: true,
        label: "IP Country Code",
        description: "The country code reported by a contact's IP address. This is automatically set by HubSpot and can be used for segmentation and reporting.",
        groupName: "conversioninformation",
        type: "string",
        fieldType: "text",
        hidden: false,
        options: [],
        formField: false,
        displayOrder: -1,
        readOnlyDefinition: true,
        mutableDefinitionNotDeletable: false,
        calculated: false,
    });

    properties["ip_latlon"] = new ContactProperty("ip_latlon", {
        // This field is used to indentify that this property was generated during importing existing properties.
        // Autogenerated fields are not editable. So if you try and change a value in this object you will fail.
        // If you want to edit this field, remove this field. Do so at your own peril.
        autoGeneratedViaImport: true,
        label: "IP Latitude & Longitude",
        description: "",
        groupName: "conversioninformation",
        type: "string",
        fieldType: "text",
        hidden: true,
        options: [],
        formField: false,
        displayOrder: -1,
        readOnlyDefinition: true,
        mutableDefinitionNotDeletable: false,
        calculated: false,
    });

    properties["ip_state"] = new ContactProperty("ip_state", {
        // This field is used to indentify that this property was generated during importing existing properties.
        // Autogenerated fields are not editable. So if you try and change a value in this object you will fail.
        // If you want to edit this field, remove this field. Do so at your own peril.
        autoGeneratedViaImport: true,
        label: "IP State/Region",
        description: "The state or region reported by a contact's IP address. This is automatically set by HubSpot and can be used for segmentation and reporting.",
        groupName: "conversioninformation",
        type: "string",
        fieldType: "text",
        hidden: false,
        options: [],
        formField: false,
        displayOrder: -1,
        readOnlyDefinition: true,
        mutableDefinitionNotDeletable: false,
        calculated: false,
    });

    properties["ip_state_code"] = new ContactProperty("ip_state_code", {
        // This field is used to indentify that this property was generated during importing existing properties.
        // Autogenerated fields are not editable. So if you try and change a value in this object you will fail.
        // If you want to edit this field, remove this field. Do so at your own peril.
        autoGeneratedViaImport: true,
        label: "IP State Code/Region Code",
        description: "The state code or region code reported by a contact's IP address. This is automatically set by HubSpot and can be used for segmentation and reporting.",
        groupName: "conversioninformation",
        type: "string",
        fieldType: "text",
        hidden: false,
        options: [],
        formField: false,
        displayOrder: -1,
        readOnlyDefinition: true,
        mutableDefinitionNotDeletable: false,
        calculated: false,
    });

    properties["ip_zipcode"] = new ContactProperty("ip_zipcode", {
        // This field is used to indentify that this property was generated during importing existing properties.
        // Autogenerated fields are not editable. So if you try and change a value in this object you will fail.
        // If you want to edit this field, remove this field. Do so at your own peril.
        autoGeneratedViaImport: true,
        label: "IP Zipcode",
        description: "The zipcode reported by a contact's IP address. This is automatically set by HubSpot and can be used for segmentation and reporting.",
        groupName: "conversioninformation",
        type: "string",
        fieldType: "text",
        hidden: true,
        options: [],
        formField: false,
        displayOrder: -1,
        readOnlyDefinition: true,
        mutableDefinitionNotDeletable: false,
        calculated: false,
    });

    properties["num_conversion_events"] = new ContactProperty("num_conversion_events", {
        // This field is used to indentify that this property was generated during importing existing properties.
        // Autogenerated fields are not editable. So if you try and change a value in this object you will fail.
        // If you want to edit this field, remove this field. Do so at your own peril.
        autoGeneratedViaImport: true,
        label: "Number of Form Submissions",
        description: "The number of forms this contact has submitted",
        groupName: "conversioninformation",
        type: "number",
        fieldType: "number",
        hidden: false,
        options: [],
        formField: false,
        displayOrder: -1,
        readOnlyDefinition: true,
        mutableDefinitionNotDeletable: false,
        calculated: true,
    });

    properties["num_unique_conversion_events"] = new ContactProperty("num_unique_conversion_events", {
        // This field is used to indentify that this property was generated during importing existing properties.
        // Autogenerated fields are not editable. So if you try and change a value in this object you will fail.
        // If you want to edit this field, remove this field. Do so at your own peril.
        autoGeneratedViaImport: true,
        label: "Number of Unique Forms Submitted",
        description: "The number of different forms this contact has submitted",
        groupName: "conversioninformation",
        type: "number",
        fieldType: "number",
        hidden: false,
        options: [],
        formField: false,
        displayOrder: -1,
        readOnlyDefinition: true,
        mutableDefinitionNotDeletable: false,
        calculated: true,
    });

    properties["recent_conversion_date"] = new ContactProperty("recent_conversion_date", {
        // This field is used to indentify that this property was generated during importing existing properties.
        // Autogenerated fields are not editable. So if you try and change a value in this object you will fail.
        // If you want to edit this field, remove this field. Do so at your own peril.
        autoGeneratedViaImport: true,
        label: "Recent Conversion Date",
        description: "The date this contact last submitted a form",
        groupName: "conversioninformation",
        type: "datetime",
        fieldType: "date",
        hidden: false,
        options: [],
        formField: false,
        displayOrder: -1,
        readOnlyDefinition: true,
        mutableDefinitionNotDeletable: false,
        calculated: true,
    });

    properties["recent_conversion_event_name"] = new ContactProperty("recent_conversion_event_name", {
        // This field is used to indentify that this property was generated during importing existing properties.
        // Autogenerated fields are not editable. So if you try and change a value in this object you will fail.
        // If you want to edit this field, remove this field. Do so at your own peril.
        autoGeneratedViaImport: true,
        label: "Recent Conversion",
        description: "The last form this contact submitted",
        groupName: "conversioninformation",
        type: "string",
        fieldType: "text",
        hidden: false,
        options: [],
        formField: false,
        displayOrder: -1,
        readOnlyDefinition: true,
        mutableDefinitionNotDeletable: false,
        calculated: true,
    });

    return properties;
};
